apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
  labels:
    app: storageos
provisioner: kubernetes.io/storageos # Native Driver reference
parameters:
  fsType: ext4
  pool: default
  adminSecretNamespace: default
  adminSecretName: storageos-api
